concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}
jobs:
  build:
    name: JDK ${{ matrix.java }} on ${{ matrix.os }} with Error Prone ${{ matrix.epVersion
      }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out NullAway sources
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDKs
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '21

          17

          ${{ matrix.java }}

          '
    - continue-on-error: true
      env:
        ORG_GRADLE_PROJECT_epApiVersion: ${{ matrix.epVersion }}
      name: Build and test using Java ${{ matrix.java }} and Error Prone ${{ matrix.epVersion
        }}
      uses: gradle/gradle-build-action@v3
      with:
        arguments: build
    - continue-on-error: true
      if: runner.os == 'Linux'
      name: Run shellcheck
      uses: gradle/gradle-build-action@v3
      with:
        arguments: shellcheck
    - continue-on-error: true
      env:
        ORG_GRADLE_PROJECT_epApiVersion: ${{ matrix.epVersion }}
      id: jacoco_report
      if: runner.os == 'Linux' && matrix.java == '11' && matrix.epVersion == '2.26.1'
        && github.repository == 'uber/NullAway'
      name: Aggregate jacoco coverage
      uses: gradle/gradle-build-action@v3
      with:
        arguments: codeCoverageReport
    - continue-on-error: true
      if: steps.jacoco_report.outcome == 'success'
      name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: ./code-coverage-report/build/reports/jacoco/codeCoverageReport/codeCoverageReport.xml
        token: ${{ secrets.CODECOV_TOKEN }}
    - continue-on-error: true
      env:
        ORG_GRADLE_PROJECT_RELEASE_SIGNING_ENABLED: 'false'
        ORG_GRADLE_PROJECT_VERSION_NAME: 0.0.0.1-LOCAL
        ORG_GRADLE_PROJECT_epApiVersion: ${{ matrix.epVersion }}
      if: matrix.java == '11'
      name: Test publishToMavenLocal flow
      uses: gradle/gradle-build-action@v3
      with:
        arguments: publishToMavenLocal
    - continue-on-error: true
      name: Check that Git tree is clean after build and test
      run: ./.buildscript/check_git_clean.sh
    strategy:
      fail-fast: false
      matrix:
        include:
        - epVersion: 2.10.0
          java: 11
          os: ubuntu-latest
        - epVersion: 2.10.0
          java: 17
          os: ubuntu-latest
        - epVersion: 2.26.1
          java: 11
          os: macos-latest
        - epVersion: 2.26.1
          java: 11
          os: ubuntu-latest
        - epVersion: 2.26.1
          java: 11
          os: windows-latest
        - epVersion: 2.26.1
          java: 17
          os: ubuntu-latest
  publish_snapshot:
    if: github.event_name == 'push' && github.repository == 'uber/NullAway' && github.ref
      == 'refs/heads/master'
    name: Publish snapshot
    needs:
    - build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out repository
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '21

          11

          '
    - continue-on-error: true
      env:
        ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD
          }}
        ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME
          }}
      name: Publish
      uses: gradle/gradle-build-action@v3
      with:
        arguments: clean publish --no-daemon --no-parallel
name: Continuous integration
on:
  repository_dispatch:
    types: trigger-ga___continuous-integration.yml
