concurrency: all
jobs:
  benchmarking:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/benchmark')
      && github.repository == 'uber/NullAway'
    permissions: write-all
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Add reaction
      uses: peter-evans/create-or-update-comment@v3
      with:
        comment-id: ${{ github.event.comment.id }}
        reactions: '+1'
    - continue-on-error: true
      name: Checkout repository
      uses: actions/checkout@v3
    - continue-on-error: true
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Set branch name
      run: "chmod +x ./.github/workflows/get_repo_details.sh \n./.github/workflows/get_repo_details.sh\
        \ \"${{ secrets.GITHUB_TOKEN }}\" \"${{ github.event.issue.number }}\" \"\
        ${{ github.repository }}\"\n"
    - continue-on-error: true
      id: auth
      name: Authenticating
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY_1 }}
    - continue-on-error: true
      name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
    - continue-on-error: true
      name: Start VM
      run: gcloud compute instances start nullway-jmh --zone=us-central1-a
    - continue-on-error: true
      name: Run benchmarks
      run: "chmod +x ./.github/workflows/run_gcp_benchmarks.sh\n./.github/workflows/run_gcp_benchmarks.sh\
        \ \n"
    - continue-on-error: true
      if: always()
      name: Cleanup
      run: './.github/workflows/gcloud_ssh.sh " export BRANCH_NAME=${BRANCH_NAME}
        && rm -r -f $BRANCH_NAME"

        '
    - continue-on-error: true
      name: Formatting Benchmark
      run: '(echo ''Main Branch:''; echo ''```'' ; cat main_text.txt; echo ''```'';
        echo ''With This PR:''; echo ''```'' ; cat pr_text.txt; echo ''```'') > benchmark.txt

        '
    - continue-on-error: true
      if: always()
      name: Comment Benchmark
      uses: mshick/add-pr-comment@v2
      with:
        message-id: benchmark
        message-path: benchmark.txt
    - continue-on-error: true
      if: always()
      name: Stop VM
      run: gcloud compute instances stop nullway-jmh --zone=us-central1-a
name: Run JMH Benchmarks for Pull Request
on:
  repository_dispatch:
    types: trigger-ga___jmh-benchmark.yml
